package constants

// Byte constants for common characters.
const (
	ByteSpace            = ' '
	ByteColon            = ':'
	ByteSemicolon        = ';'
	ByteSlash            = '/'
	ByteAsterisk         = '*'
	ByteDot              = '.'
	ByteComma            = ','
	ByteHyphen           = '-'
	ByteUnderscore       = '_'
	ByteAt               = '@'
	ByteHash             = '#'
	ByteDollar           = '$'
	BytePercent          = '%'
	BytePlus             = '+'
	ByteMinus            = '-'
	ByteEquals           = '='
	ByteAmpersand        = '&'
	BytePipe             = '|'
	ByteTilde            = '~'
	ByteBacktick         = '`'
	ByteQuestionMark     = '?'
	ByteExclamationMark  = '!'
	ByteLeftParenthesis  = '('
	ByteRightParenthesis = ')'
	ByteLeftBracket      = '['
	ByteRightBracket     = ']'
	ByteLeftBrace        = '{'
	ByteRightBrace       = '}'
	ByteDoubleQuote      = '"'
	ByteSingleQuote      = '\''
	ByteBackslash        = '\\'
	ByteCarriageReturn   = '\r'
	ByteNewline          = '\n'
	ByteTab              = '\t'
)
