package constants

// String constants for common characters and sequences.
const (
	Empty                 = ""
	Space                 = " "
	Colon                 = ":"
	ColonSpace            = ": "
	Semicolon             = ";"
	Slash                 = "/"
	DoubleSlash           = "//"
	Asterisk              = "*"
	Dot                   = "."
	Comma                 = ","
	CommaSpace            = ", "
	Hyphen                = "-"
	Underscore            = "_"
	At                    = "@"
	Hash                  = "#"
	Dollar                = "$"
	Percent               = "%"
	Plus                  = "+"
	Minus                 = "-"
	Equals                = "="
	Ampersand             = "&"
	Pipe                  = "|"
	Tilde                 = "~"
	Backtick              = "`"
	QuestionMark          = "?"
	ExclamationMark       = "!"
	LeftParenthesis       = "("
	RightParenthesis      = ")"
	LeftBracket           = "["
	RightBracket          = "]"
	LeftBrace             = "{"
	RightBrace            = "}"
	DoubleQuote           = "\""
	SingleQuote           = "'"
	Backslash             = "\\"
	CarriageReturn        = "\r"
	Newline               = "\n"
	CarriageReturnNewline = "\r\n"
	Tab                   = "\t"
)
